version: "3"

services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=tetim
        ports:
          - "5432:5432"
        volumes: 
          - db:/var/lib/postgresql/data
    app:
        build:
          context: flask_tetim
        ports:
          - "5000"
        depends_on:
            - db
        restart: on-failure:10
        env_file: .env
        environment:
            - SECRET_KEY=${SECRET_KEY}
    nginx:
        image: nginx:latest
        volumes:
            - ./flask_tetim/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - "80:80"
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
          - "5050:80"
volumes:
    db:
        driver: local




